# Generated by Django 5.2.15 on 2026-06-11 12:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('static_qr_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('hold', 'Hold'), ('reversal', 'Reversal')], max_length=8)),
                ('amount', models.BigIntegerField(help_text='Tiyin (1/100 UZS), strictly positive')),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Idempotency key', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('related_entry', models.ForeignKey(blank=True, help_text='For reversal entries: the hold entry being released', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='core.ledgerentry')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_as_credit', to='core.ledgerentry')),
                ('debit_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_as_debit', to='core.ledgerentry')),
            ],
        ),
    ]
