# Generated by Django 5.2.15 on 2026-06-11 12:17

import apps.core.state
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('otp_pending', 'OTP pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='initiated', max_length=16)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.wallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.wallet')),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request', to='core.transfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(apps.core.state.StateMachineMixin, models.Model),
        ),
    ]
